source 'https://rubygems.org'

gem 'bcrypt'
gem 'i18n'
gem 'jwt'
gem 'mail'
gem 'net-sftp'
gem 'pg'
gem 'prawn'
gem 'prawn-table'
gem 'puma'
gem 'rack'
gem 'rack-cors'
gem 'rake'
gem 'roda'
gem 'rodauth'
gem 'rrtf'
gem 'rubyzip'
gem 'rufus-scheduler'
gem 'savon'
gem 'sequel'
gem 'sequel-pg-trgm'
gem 'tilt'
gem 'zlib'
gem 'rqrcode'

# Test requirements
group :test, :development do
  gem 'debase'
  gem 'factory_bot'
  gem 'faker'
  gem 'gem-licenses'
  gem 'minitest'
  gem 'minitest-hooks'
  gem 'minitest-reporters'
  gem 'minitest-sequel'
  gem 'rack-test'
  gem 'roda-route_list'
  gem 'uuid'
  gem 'webrick'
  gem 'yard'
  # correct new 1.0 version wasn't marked as release, neither on Github nor on rubygems
  gem 'json_schemer'
  gem 'prmd'
  gem 'pry'
  gem 'rerun'
  gem 'ruby-debug-ide'
  gem 'yard-appendix'
  gem 'yard-doctest'
  gem 'yard-minitest-spec'
end
